if (WIN32)
    set(superhack_OS_WIN ON)
elseif (APPLE)
    set(superhack_OS_APPLE ON)

    if (IOS OR CMAKE_SYSTEM_NAME STREQUAL iOS)
        set(superhack_OS_IOS ON)
    else()
        set(superhack_OS_MACOS ON)
    endif()
else()
    set(superhack_OS_UNIX ON)

    if (ANDROID OR CMAKE_SYSTEM_NAME MATCHES "Android")
        set(superhack_OS_ANDROID ON)
    elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
        set(superhack_OS_LINUX ON)
    elseif(CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
        set(superhack_OS_FREEBSD ON)
    endif()
endif()


if (superhack_OS_WIN)
    add_definitions(/DWIN32)
    add_definitions(/Dsuperhack_OS_WIN)
elseif(superhack_OS_APPLE)
    add_definitions(/Dsuperhack_OS_APPLE)

    if (superhack_OS_IOS)
        add_definitions(/Dsuperhack_OS_IOS)
    else()
        add_definitions(/Dsuperhack_OS_MACOS)
    endif()
elseif(superhack_OS_UNIX)
    add_definitions(/Dsuperhack_OS_UNIX)

    if (superhack_OS_ANDROID)
        add_definitions(/Dsuperhack_OS_ANDROID)
    elseif (superhack_OS_LINUX)
        add_definitions(/Dsuperhack_OS_LINUX)
    elseif (superhack_OS_FREEBSD)
        add_definitions(/Dsuperhack_OS_FREEBSD)
    endif()
endif()
